version: '3'
services:
  api-server:
    build: .
    ports:
      - '3000:3000'
    container_name: node-api
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo:3
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    ports:
      - '3001:3001'
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
    links:
      - api-server
