version: '3'
services:
  api-server:
    context: ./
    dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    container_name: node-api
    links:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo:3
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web.prod
    ports:
      - '3001:3001'
    links:
      - api-server
